version: '3.9'

services:
  blockscout:
    image: 0xethernal/blockscout:6.5.0-beta
    container_name: 'blockscout'
    command: bash -c "scripts/run.sh"
    env_file:
      - /opt/blockscout/blockscout.env
    volumes:
      - ./logs/:/explorer/logs/
    ports:
      - "4000:4000"
