version: '3.9'

services:
  blockscout:
    image: 0xethernal/blockscout:6.5.0.1-beta
    container_name: 'blockscout'
    command: bash -c "scripts/db-create.sh && scripts/start-blockscout.sh"
    env_file:
      - /opt/blockscout/blockscout.env
    volumes:
      - ./logs/:/explorer/blockscout/logs/
    ports:
      - "4000:4000"
