version: '3.9'

services:
  db:
    extends:
      file: ./services/db.yml
      service: db
  blockscout:
    depends_on:
      db:
        condition: service_healthy
    extends:
      file: ./services/blockscout.yml
      service: blockscout
  sc-verifier:
    extends:
      file: ./services/sc-verifier.yml
      service: sc-verifier
