version: '3.9'

services:
  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
  blockscout:
    depends_on:
      db:
        condition: service_healthy
    extends:
      file: ./services/blockscout.yml
      service: blockscout
